// <auto-generated />
namespace ShoeStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ValidBackToNormal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidBackToNormal));
        
        string IMigrationMetadata.Id
        {
            get { return "202511121422252_ValidBackToNormal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
